### ISSUE TITLE
偶现摄像头开启预览异常，直接崩溃

### ISSUE THREAD

**Issue by Leavds** [Faceunity/FuAgoraDemoDroid#6]
java.lang.RuntimeException: Unable to resume activity {com.yidi.minilive/com.yidi.livelibrary.ui.anchor.activity.HnAnchorActivity}: java.lang.RuntimeException: startPreview failed
at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3830)
at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3870)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3090)
at android.app.ActivityThread.-wrap11(Unknown Source:0)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1739)
at android.os.Handler.dispatchMessage(Handler.java:106)
at android.os.Looper.loop(Looper.java:164)
at android.app.ActivityThread.main(ActivityThread.java:7036)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:441)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1408)
Caused by: java.lang.RuntimeException: startPreview failed
at android.hardware.Camera.startPreview(Native Method)
at com.yidi.livelibrary.fu.FuTextureCamera.previewCamera(FuTextureCamera.java:136)
at com.yidi.livelibrary.fu.FuTextureCamera.onResume(FuTextureCamera.java:45)
at com.yidi.livelibrary.ui.anchor.activity.HnAnchorActivity.fuTextureCameraOnResume(HnAnchorActivity.java:1086)
at com.yidi.livelibrary.ui.anchor.activity.HnAnchorActivity.onResume(HnAnchorActivity.java:383)
at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1363)
at android.app.Activity.performResume(Activity.java:7444)
at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3805)
... 10 more
java.lang.RuntimeException: startPreview failed
at android.hardware.Camera.startPreview(Native Method)
at com.yidi.livelibrary.fu.FuTextureCamera.previewCamera(FuTextureCamera.java:136)
at com.yidi.livelibrary.fu.FuTextureCamera.onResume(FuTextureCamera.java:45)
at com.yidi.livelibrary.ui.anchor.activity.HnAnchorActivity.fuTextureCameraOnResume(HnAnchorActivity.java:1086)
at com.yidi.livelibrary.ui.anchor.activity.HnAnchorActivity.onResume(HnAnchorActivity.java:383)
at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1363)
at android.app.Activity.performResume(Activity.java:7444)
at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3805)
at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3870)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3090)
at android.app.ActivityThread.-wrap11(Unknown Source:0)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1739)
at android.os.Handler.dispatchMessage(Handler.java:106)
at android.os.Looper.loop(Looper.java:164)
at android.app.ActivityThread.main(ActivityThread.java:7036)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:441)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1408)

**Comment by git-xuhao** [comment]
@Leavds  我在某些机型也出现了类似这样的问题，直接奔溃，统计到的异常，请问后来解决了吗？
`


# Thread-4425(4425)

java.lang.RuntimeException
     Fail to connect to camera service

1 android.hardware.Camera.<init>(Camera.java:619)
2 android.hardware.Camera.open(Camera.java:414)
3 com.miyan.agora.fu.FuTextureCamera.openCamera(FuTextureCamera.java:150)
4 com.miyan.agora.fu.FuTextureCamera.onCapturerOpened(FuTextureCamera.java:66)
5 com.miyan.agora.fu.FuTextureSource.onInitialize(FuTextureSource.java:35)


`
